name: jbook
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-book==0.13.1
  - pandas==1.2.4
  - numpy==1.21.6
  - matplotlib==3.4.3
  - plotly==5.9.0
  - seaborn==0.12.1
  - umap-learn==0.5.3
  - numba==0.56.3
  - jupyterlab